name: test

on:
  push:
    branches:
      - fix/build_action

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'
      - uses: mxschmitt/action-tmate@v3
      # 同じ日に 2 回目以上のデプロイが走った場合はタグを YYYY-mm-dd-n とする
      - name: Create new tag
        id: create_tag
        env:
          TZ: 'Asia/Tokyo'
        run: |
          TODAY=$(date +'%Y-%m-%d')
          COUNT=`git tag -l "$TODAY*" | wc -l`
          echo `git tag | grep "$TODAY"`
          echo $TODAY
          echo $COUNT

          if [ $COUNT -gt 0 ] ; then
            NEW_TAG="$TODAY-$((COUNT += 1))"
          else
            NEW_TAG=$TODAY
          fi
          echo "::set-output name=date::$TODAY"
          echo "::set-output name=time::$(date +'%H:%M:%S')"
          echo "::set-output name=new_tag::$NEW_TAG"
      - name: Test Created new tag
        run: |
          echo "Release ${{ steps.create_tag.outputs.new_tag }}"
